### ISSUE TITLE
Can we have the whole statusline the same color?

### ISSUE THREAD

**Issue by justrajdeep** [jssteinberg/hackline.vim#2]
Hi

Use the statusline to identify the files, is it possible to have them the full color for a selected buffer similar to an unselected buffer?

![image](https://user-images.githubusercontent.com/3525867/176260691-6f95db97-29f1-4769-8eb4-b924d81be855.png)

**Comment by jssteinberg** [comment]
I can add an option for it. Do you think the whole line should change color for different modes?

**Comment by justrajdeep** [comment]
Hi 

I am fine with changing color or not based on whatever you prefer, I just want it to be same color so that visually it is very clear for me where one file ends and another one begins.

**Comment by jssteinberg** [comment]
Just merged an update. Now you can change highlight group of all colors in statusline. So to get what you asked for (in normal mode) you can do:

```vim
let g:hackline_highlight_normal    = 'StatusLine'
let g:hackline_highlight_secondary = 'StatusLine'
let g:hackline_highlight_items     = 'StatusLine'
let g:hackline_hightlight_branch   = 'StatusLine'
let g:hackline_highlight_end       = 'StatusLine'
```

You can also use same colors for all other modes:

```vim
let g:hackline_highlight_insert   = 'StatusLine'
let g:hackline_highlight_visual   = 'StatusLine'
let g:hackline_highlight_replace  = 'StatusLine'
let g:hackline_highlight_select   = 'StatusLine'
let g:hackline_highlight_command  = 'StatusLine'
let g:hackline_highlight_terminal = 'StatusLine'
```
![Screenshot 2022-06-29 at 22 25 51](https://user-images.githubusercontent.com/729055/176538288-cc71dbef-3b77-477c-9ac9-14daae269eda.png)
